export enum userActionTypes {
  USER_LOGIN = "USER_LOGIN",
  USER_LOGOUT = "USER_LOGOUT",
  USER_SIGNUP = "USER_SIGNUP",
  USER_ADD_ITEM_TO_CART = "USER_ADD_ITEM_TO_CART",
  USER_UPDATE_ITEM_FROM_CART = "USER_UPDATE_ITEM_FROM_CART",
  USER_REMOVE_ITEM_FROM_CART = "USER_REMOVE_ITEM_FROM_CART"
}