export enum userActionTypes {
  USER_LOGIN_WITH_REJECT = "USER_LOGIN_WITH_REJECT",
  USER_LOGIN_WITH_RESOLVE = "USER_LOGIN_WITH_RESOLVE",
  USER_LOGOUT = "USER_LOGOUT",
  USER_SIGNUP = "USER_SIGNUP"
}