export enum productActionTypes {
  ADD_FAVORITE_PRODUCTS_WITH_RESOLVE = "ADD_FAVORITE_PRODUCTS_WITH_RESOLVE",
  ADD_FAVORITE_PRODUCTS_WITH_REJECT = "ADD_FAVORITE_PRODUCTS_WITH_REJECT",
  ADD_PRODUCTS_TO_STORE_WITH_RESOLVE = "ADD_PRODUCTS_TO_STORE_WITH_RESOLVE",
  ADD_PRODUCTS_TO_STORE_WITH_REJECT = "ADD_PRODUCTS_TO_STORE_WITH_REJECT",
  RESET_VALUE_PRODUCTS = "RESET_VALUE_PRODUCTS"
}