export enum productActionTypes {
  ADD_FAVORITE_PRODUCTS_WITH_RESOLVE = "ADD_FAVORITE_PRODUCTS_WITH_RESOLVE",
  ADD_FAVORITE_PRODUCTS_WITH_REJECT = "ADD_FAVORITE_PRODUCTS_WITH_REJECT",
  ADD_PRODUCTS_TO_STORES = "ADD_PRODUCTS_TO_STORES"
}