export enum configActionType {
  RESOLVE_ADD_CONFIG_BANNERS = "RESOLVE_ADD_CONFIG_BANNERS",
  REJECT_ADD_CONFIG_BANNERS = "REJECT_ADD_CONFIG_BANNERS",
  SET_BANNER_IN_NAVBAR_DISMISS = "SET_BANNER_IN_NAVBAR_DISMISS"
};